# Dependencies
markdown: kramdown
highlighter: pygments

# Kramdown Options
kramdown:
  math_engine: mathjax
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ML_blog
tagline:          'A Jekyll theme'
description:      ' Posting about machine learning and data-science for hobby'
url:              https://hyde.getpoole.com
baseurl: /ml_ds_blog


author:
  name:           'John Han'
  url:            httpss://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-katex

include:
  - _layouts
